# JVM Settings (High Performance)
# Xmx8G is plenty for most builds. UseParallelGC improves throughput.
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=1G -XX:+UseParallelGC

# Gradle Performance Options
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

# Android / Kotlin Optimizations
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=true
kotlin.incremental.java=true
kotlin.incremental.js=true
