// Mocks generated by Mockito 5.4.4 from annotations
// in crossbar/test/services/refresh_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:crossbar/core/plugin_manager.dart' as _i4;
import 'package:crossbar/models/plugin.dart' as _i2;
import 'package:crossbar/models/plugin_output.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlugin_0 extends _i1.SmartFake implements _i2.Plugin {
  _FakePlugin_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PluginManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPluginManager extends _i1.Mock implements _i4.PluginManager {
  MockPluginManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Plugin> get plugins => (super.noSuchMethod(
        Invocation.getter(#plugins),
        returnValue: <_i2.Plugin>[],
      ) as List<_i2.Plugin>);

  @override
  set customPluginsDirectory(String? path) => super.noSuchMethod(
        Invocation.setter(
          #customPluginsDirectory,
          path,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<String> get pluginsDirectory => (super.noSuchMethod(
        Invocation.getter(#pluginsDirectory),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> discoverPlugins() => (super.noSuchMethod(
        Invocation.method(
          #discoverPlugins,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.PluginOutput>> runAllEnabled() => (super.noSuchMethod(
        Invocation.method(
          #runAllEnabled,
          [],
        ),
        returnValue: _i5.Future<List<_i6.PluginOutput>>.value(<_i6.PluginOutput>[]),
      ) as _i5.Future<List<_i6.PluginOutput>>);

  @override
  _i5.Future<_i6.PluginOutput?> runPlugin(String? pluginId) =>
      (super.noSuchMethod(
        Invocation.method(
          #runPlugin,
          [pluginId],
        ),
        returnValue: _i5.Future<_i6.PluginOutput?>.value(),
      ) as _i5.Future<_i6.PluginOutput?>);

  @override
  _i5.Future<void> togglePlugin(String? pluginId) => (super.noSuchMethod(
        Invocation.method(
          #togglePlugin,
          [pluginId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> enablePlugin(String? pluginId) => (super.noSuchMethod(
        Invocation.method(
          #enablePlugin,
          [pluginId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> disablePlugin(String? pluginId) => (super.noSuchMethod(
        Invocation.method(
          #disablePlugin,
          [pluginId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i2.Plugin? getPlugin(String? pluginId) =>
      (super.noSuchMethod(Invocation.method(
        #getPlugin,
        [pluginId],
      )) as _i2.Plugin?);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
