#!/bin/bash
# Crossbar submenu demo plugin
# Demonstrates nested menus using BitBar format

echo "📊 System | color=blue"
echo "---"
echo "Hardware"
echo "--CPU"
echo "----Model: $(lscpu | grep 'Model name' | cut -d: -f2 | xargs)"
echo "----Cores: $(nproc)"
echo "----Usage: $(top -bn1 | grep 'Cpu(s)' | awk '{print $2}')%"
echo "--Memory"
echo "----Total: $(free -h | awk '/Mem:/ {print $2}')"
echo "----Used: $(free -h | awk '/Mem:/ {print $3}')"
echo "----Free: $(free -h | awk '/Mem:/ {print $4}')"
echo "--Storage"
echo "----Root: $(df -h / | awk 'NR==2 {print $3 "/" $2}')"
echo "----Home: $(df -h /home | awk 'NR==2 {print $3 "/" $2}')"
echo "---"
echo "Quick Actions"
echo "--Open Terminal | bash=gnome-terminal"
echo "--Open File Manager | bash=nautilus"
echo "---"
echo "Network"
echo "--IP Address"
echo "----Local: $(hostname -I | cut -d' ' -f1)"
echo "----Public: $(curl -s ifconfig.me 2>/dev/null || echo 'N/A') | href=https://ifconfig.me"
echo "--Status"
echo "----$(ping -c1 -W1 8.8.8.8 &>/dev/null && echo '🟢 Online' || echo '🔴 Offline')"
