name: crossbar_api
description: Official Dart API for creating compiled Crossbar plugins with full IntelliSense support
version: 0.1.0
repository: https://github.com/verseles/crossbar
homepage: https://github.com/verseles/crossbar

environment:
  sdk: ^3.4.0

dependencies:
  dio: ^5.4.0
  crypto: ^3.0.3
  uuid: ^4.5.0
  intl: ^0.18.1

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.0
